// frontend/script.js

// 1. Auto-detect URL (Works on Localhost AND Railway)
const BASE_URL = window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
  ? "http://127.0.0.1:5000"
  : "https://ai-skill-gap-generator-production.up.railway.app";

const zipBase = "https://raw.githubusercontent.com/dhansuhkumar/ai-skill-gap-generator/main/backend/projects/";
let skillChartInstance = null;

document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('recommendForm');
  const loading = document.getElementById('loading');
  const results = document.getElementById('results');

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    results.classList.add('hidden');
    loading.classList.remove('hidden');

    const skillsInput = document.getElementById('skills').value;
    const skills = skillsInput.split(',').map(s => s.trim()).filter(s => s);
    const role = document.getElementById('role').value;
    
    // FIX: Your backend (auth.py) requires 'username', not 'user_id'
    try {
      const authRes = await fetch(`${BASE_URL}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: "dhanush", password: "securepassword123" })
      });
      
      if(authRes.ok) {
          const authData = await authRes.json();
          localStorage.setItem("jwtToken", authData.access_token);
      }
    } catch (err) {
      console.warn("Login skipped or failed (Dev mode):", err);
    }

    try {
      //  Step 1: Get recommendations
      const response = await fetch(`${BASE_URL}/api/recommend`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ role, skills })
      });

      if (!response.ok) throw new Error("Failed to fetch recommendations");
      const data = await response.json();

      //  Step 2: Save profile (Silent fail if no token)
      const token = localStorage.getItem("jwtToken");
      if (token) {
        fetch(`${BASE_URL}/api/save_profile`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${token}`
            },
            body: JSON.stringify({ role, skills, recommendations: ["Generated by AI"] })
        }).catch(e => console.log("Save profile ignored"));
      }

      //  Step 3: Update the NEW UI (Glassmorphism)
      
      // A. Missing Skills (Tags)
      const missingContainer = document.getElementById('missingSkillsList');
      if (missingContainer) {
          missingContainer.innerHTML = (data.missing_skills || []).map(skill => 
            `<span class="bg-yellow-500/20 text-yellow-200 border border-yellow-500/30 px-3 py-1 rounded-full text-sm font-medium">
              ${skill}
             </span>`
          ).join('');
      }

    // frontend/script.js (REPLACE ENTIRE Section B)

      // B. Projects (Cards)
      const projectContainer = document.getElementById('projectContainer');
      if (projectContainer) {
          
          // 1. Recommended Projects (The core list)
          const projectsHTML = (data.recommended_projects || []).map(p => `
            <div class="hover:bg-white/5 p-4 rounded-xl border border-white/10 transition hover:-translate-y-1 mb-3">
                <h4 class="text-lg font-bold text-blue-200">${p.skill}</h4>
                <p class="text-gray-300 text-sm mt-1">${p.project}</p>
            </div>
          `).join('');

          // 2. Starter Code (The ZIP file downloads)
          const starterHTML = (data.starter_projects || []).map(zipPath => {
            const filename = zipPath.split(/[\\/]/).pop();
            return `
            <div class="bg-purple-500/10 p-4 rounded-xl border border-purple-500/30 mb-3 flex justify-between items-center transition hover:bg-purple-500/20">
                <div class="flex items-center gap-3">
                    <div class="text-2xl">📦</div>
                    <div>
                        <h4 class="text-md font-bold text-purple-200">Starter Code: ${filename}</h4>
                    </div>
                </div>
                <a href="${zipBase}${filename}" download="${filename}" 
                   class="bg-purple-600 hover:bg-purple-500 text-white px-4 py-2 rounded-lg text-sm font-bold">
                  Download
                </a>
            </div>
            `;
          }).join('');

          // 3. 🤖 AI Project Ideas (THIS IS WHERE THE AI DATA IS DISPLAYED)
          // The block only renders if the list is NOT empty
          const aiIdeasHTML = (data.ai_projects && data.ai_projects.length > 0) ? `
              <div class="bg-indigo-500/10 p-4 rounded-2xl border border-indigo-500/30 mb-6 shadow-lg">
                  <h3 class="text-xl font-bold text-indigo-300 mb-3 flex items-center gap-2">
                      <span class="text-2xl">🤖</span> AI-Generated Project Ideas
                  </h3>
                  <ul class="list-disc pl-5 space-y-2 text-gray-200">
                      ${data.ai_projects.map(idea => `<li>${idea}</li>`).join('')}
                  </ul>
              </div>
          ` : '';
          
          // ✅ CRITICAL FIX: Include aiIdeasHTML in the final output string!
          projectContainer.innerHTML = aiIdeasHTML + projectsHTML + starterHTML;
      }
// ... (rest of your script.js continues from section C. Chart)

      // C. Chart
      const allSkills = [...skills, ...(data.missing_skills || [])];
      const uniqueSkills = [...new Set(allSkills)];
      const skillColors = uniqueSkills.map(s => skills.includes(s) ? '#4ade80' : '#f87171');
      
      const ctx = document.getElementById('skillChart').getContext('2d');
      if (skillChartInstance) skillChartInstance.destroy();
      
      skillChartInstance = new Chart(ctx, {
        type: 'doughnut',
        data: {
          labels: uniqueSkills,
          datasets: [{
            data: uniqueSkills.map(() => 1),
            backgroundColor: skillColors,
            borderWidth: 0
          }]
        },
        options: { responsive: true, cutout: '70%', plugins: { legend: { display: false } } }
      });

      loading.classList.add('hidden');
      results.classList.remove('hidden');
      
    } catch (error) {
      loading.classList.add('hidden');
      console.error('Error:', error);
      alert('Error: ' + error.message);
    }
  });
});

// KEEPING YOUR ORIGINAL RESUME UPLOAD FUNCTION
function uploadResume() {
  const fileInput = document.getElementById("resumeUpload");
  const file = fileInput.files[0];
  if (!file) return alert("Please select a PDF file.");

  const formData = new FormData();
  formData.append("file", file);

  fetch(`${BASE_URL}/api/upload_resume`, { method: "POST", body: formData })
    .then(res => res.json())
    .then(data => {
      const skillsInput = document.getElementById("skills");
      const manual = skillsInput.value.split(",").map(s => s.trim()).filter(s => s);
      const merged = [...new Set([...manual, ...(data.extracted_skills || [])])];
      skillsInput.value = merged.join(", ");
      alert("✅ Skills Extracted!");
    })
    .catch(err => { console.error(err); alert("Upload failed."); });
}