// frontend/script.js

// 1. Auto-detect backend URL
const isLocal =
  window.location.hostname === "localhost" ||
  window.location.hostname === "127.0.0.1" ||
  window.location.protocol === "file:";

const BASE_URL = isLocal
  ? "http://127.0.0.1:8080"
  : "https://ai-skill-gap-generator-production.up.railway.app";

const zipBase =
  "https://raw.githubusercontent.com/dhansuhkumar/ai-skill-gap-generator/main/backend/projects/";

let skillChartInstance = null;

document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("recommendForm");
  const loading = document.getElementById("loading");
  const results = document.getElementById("results");

  form.addEventListener("submit", async (e) => {
    e.preventDefault();
    results.classList.add("hidden");
    loading.classList.remove("hidden");

    const skillsInput = document.getElementById("skills").value;
    const skills = skillsInput
      .split(",")
      .map((s) => s.trim())
      .filter((s) => s);
    const role = document.getElementById("role").value;

    // Optional: JWT login (ignore if fails)
    try {
      const authRes = await fetch(`${BASE_URL}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          username: "dhanush",
          password: "securepassword123",
        }),
      });

      if (authRes.ok) {
        const authData = await authRes.json();
        localStorage.setItem("jwtToken", authData.access_token);
      }
    } catch (err) {
      console.warn("Login skipped/failed:", err);
    }

    try {
      const response = await fetch(`${BASE_URL}/recommend`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ role, skills }),
      });

      if (!response.ok) throw new Error("Failed to fetch recommendations");
      const data = await response.json();
      console.log("Full /recommend response:", data);

      // Save profile silently if token exists
      const token = localStorage.getItem("jwtToken");
      if (token) {
        fetch(`${BASE_URL}/api/save_profile`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            role,
            skills,
            recommendations: ["Generated by AI"],
          }),
        }).catch((e) => console.log("Save profile ignored:", e));
      }

      updateUIWithRecommendations(data, role, skills);

      loading.classList.add("hidden");
      results.classList.remove("hidden");
    } catch (error) {
      loading.classList.add("hidden");
      console.error("Error:", error);
      alert("Error: " + error.message);
    }
  });
});

// 🔧 Render results
function updateUIWithRecommendations(data, role, userSkills) {
  const missingSkills = data.missing_skills || [];
  const recommendedProjects = data.recommended_projects || [];
  const starterProjects = data.starter_projects || [];
  const aiProjects = data.ai_projects || [];
  const requiredSkillsAI = data.required_skills_ai || [];

  // A) Missing skills (tags)
  const missingContainer = document.getElementById("missingSkillsList");
  if (missingContainer) {
    if (missingSkills.length === 0) {
      missingContainer.innerHTML =
        '<span class="text-green-300 text-sm">You are a perfect match for this role!</span>';
    } else {
      missingContainer.innerHTML = missingSkills
        .map(
          (skill) => `
        <span class="bg-yellow-500/20 text-yellow-200 border border-yellow-500/30 px-3 py-1 rounded-full text-sm font-medium">
          ${skill}
        </span>
      `
        )
        .join("");
    }
  }

  // B) Core skills for the role (AI only IF present)
  const sidebar = document.getElementById("missingSkillsList")?.parentElement;
  if (sidebar && requiredSkillsAI.length > 0) {
    // Only render block if AI actually returned something
    let requiredBlock = document.getElementById("requiredSkillsBlock");
    if (!requiredBlock) {
      requiredBlock = document.createElement("div");
      requiredBlock.id = "requiredSkillsBlock";
      requiredBlock.className = "bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-4 shadow-xl mt-4";
      sidebar.parentElement.insertBefore(requiredBlock, sidebar.nextSibling);
    }
    requiredBlock.innerHTML = `
      <h3 class="text-lg font-semibold text-blue-200 mb-2">🔧 Core Skills for this Role (AI)</h3>
      <div id="requiredSkillsList" class="flex flex-wrap gap-2"></div>
    `;
    const requiredContainer = requiredBlock.querySelector("#requiredSkillsList");
    requiredContainer.innerHTML = requiredSkillsAI
      .map(
        (skill) => `
        <span class="bg-blue-500/15 text-blue-100 border border-blue-500/40 px-3 py-1 rounded-full text-xs font-medium">
          ${skill}
        </span>
      `
      )
      .join("");
  }

  // C) Projects + videos + AI ideas
  const projectContainer = document.getElementById("projectContainer");
  if (projectContainer) {
    // 1) Recommended projects (each with optional YouTube videos)
    const projectsHTML = recommendedProjects
      .map((p) => {
        const videos = p.videos || [];
        const videosHTML =
          videos.length > 0
            ? `
          <div class="mt-3 border-t border-white/10 pt-2">
            <p class="text-xs text-gray-300 mb-1">🎥 Learn this skill:</p>
            <ul class="space-y-1 text-xs">
              ${videos
                .map(
                  (v) => `
                <li>
                  <a href="${v.url}" target="_blank" class="text-blue-300 hover:underline">
                    ${v.title}
                  </a>
                  <span class="text-gray-400">· ${v.channel}</span>
                </li>
              `
                )
                .join("")}
            </ul>
          </div>
        `
            : "";

        return `
        <div class="hover:bg-white/5 p-4 rounded-xl border border-white/10 transition hover:-translate-y-1 mb-3">
          <h4 class="text-lg font-bold text-blue-200">${p.skill}</h4>
          <p class="text-gray-300 text-sm mt-1">${p.project}</p>
          ${videosHTML}
        </div>
      `;
      })
      .join("");

    // 2) Starter code ZIP downloads
    const starterHTML = starterProjects
      .map((zipPath) => {
        const filename = zipPath.split(/[\\/]/).pop();
        return `
        <div class="bg-purple-500/10 p-4 rounded-xl border border-purple-500/30 mb-3 flex justify-between items-center transition hover:bg-purple-500/20">
          <div class="flex items-center gap-3">
            <div class="text-2xl">📦</div>
            <div>
              <h4 class="text-md font-bold text-purple-200">Starter Code: ${filename}</h4>
            </div>
          </div>
          <a href="${zipBase}${filename}" download="${filename}"
             class="bg-purple-600 hover:bg-purple-500 text-white px-4 py-2 rounded-lg text-sm font-bold">
            Download
          </a>
        </div>
      `;
      })
      .join("");

    // 3) AI project ideas (titles)
    const aiIdeasHTML =
      aiProjects && aiProjects.length > 0
        ? `
      <div class="bg-indigo-500/10 p-4 rounded-2xl border border-indigo-500/30 mb-6 shadow-lg">
        <h3 class="text-xl font-bold text-indigo-300 mb-3 flex items-center gap-2">
          <span class="text-2xl">🤖</span> AI-Generated Project Ideas for: ${role}
          <span class="ml-2 text-xs bg-indigo-700 text-white px-2 py-1 rounded">Live</span>
        </h3>
        <ul class="list-disc list-inside text-indigo-100 text-sm space-y-1">
          ${aiProjects.map((idea) => `<li class="pl-2">${idea}</li>`).join("")}
        </ul>
      </div>
    `
        : "";

    projectContainer.innerHTML =
      aiIdeasHTML +
      (projectsHTML ||
        '<p class="text-gray-300 text-sm">No skill-based project suggestions available.</p>') +
      starterHTML;
  }

  // D) Skill chart: match vs missing
  const chartCanvas = document.getElementById("skillChart");
  if (chartCanvas) {
    const totalRequired =
      requiredSkillsAI.length > 0
        ? requiredSkillsAI.length
        : userSkills.length + missingSkills.length;
    const missingCount = missingSkills.length;
    const matched = Math.max(totalRequired - missingCount, 0);

    const ctx = chartCanvas.getContext("2d");
    if (skillChartInstance) {
      skillChartInstance.destroy();
    }

    skillChartInstance = new Chart(ctx, {
      type: "doughnut",
      data: {
        labels: ["Matched Skills", "Missing Skills"],
        datasets: [
          {
            data: [matched, missingCount],
          },
        ],
      },
      options: {
        responsive: true,
        plugins: {
          legend: {
            position: "bottom",
            labels: { color: "#ffffff" },
          },
        },
      },
    });
  }
}

// 📄 Resume upload handler (unchanged behavior)
async function uploadResume() {
  const fileInput = document.getElementById("resumeUpload");
  const file = fileInput.files[0];
  if (!file) {
    alert("Please choose a PDF resume first.");
    return;
  }

  const formData = new FormData();
  formData.append("file", file);

  try {
    const res = await fetch(`${BASE_URL}/api/upload_resume`, {
      method: "POST",
      body: formData,
    });
    if (!res.ok) throw new Error("Failed to upload resume");
    const data = await res.json();

    if (data.extracted_skills && Array.isArray(data.extracted_skills)) {
      const skillsInput = document.getElementById("skills");
      const manual = skillsInput.value
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s);
      const merged = [...new Set([...manual, ...data.extracted_skills])];
      skillsInput.value = merged.join(", ");
      alert("✅ Skills extracted from resume!");
    } else {
      alert("No clear skills found in resume.");
    }
  } catch (err) {
    console.error("Error uploading resume:", err);
    alert("Failed to extract skills from resume.");
  }
}
